# Generated by Django 4.0.6 on 2022-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstat',
            name='common',
            field=models.CharField(default='-1', max_length=120),
        ),
        migrations.AlterField(
            model_name='financialstat',
            name='inflation',
            field=models.CharField(default='-1', max_length=120),
        ),
        migrations.AlterField(
            model_name='financialstat',
            name='interestRate',
            field=models.CharField(default='2.50%', max_length=120),
        ),
        migrations.AlterField(
            model_name='financialstat',
            name='median',
            field=models.CharField(default='-1', max_length=120),
        ),
        migrations.AlterField(
            model_name='financialstat',
            name='trim',
            field=models.CharField(default='-1', max_length=120),
        ),
    ]
